"""empty message

Revision ID: 04660e6e8e6d
Revises: 83652a09866d
Create Date: 2021-08-06 10:14:40.407312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04660e6e8e6d'
down_revision = '83652a09866d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contract_products', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract_products', type_='foreignkey')
    # ### end Alembic commands ###
