"""empty message

Revision ID: 1bab42303aca
Revises: e0e2e9cb41a5
Create Date: 2021-08-13 09:20:42.451941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bab42303aca'
down_revision = 'e0e2e9cb41a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('contract_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'contract_types', ['contract_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'contract_type_id')
    # ### end Alembic commands ###
