"""empty message

Revision ID: 3659e9bf9856
Revises: 
Create Date: 2021-08-05 21:06:24.400153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3659e9bf9856'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contract_clauses', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'contract_clauses', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'contract_details', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['modified_by'], ['id'])
    op.create_foreign_key(None, 'products', 'users', ['created_by'], ['id'])
    op.add_column('tenders', sa.Column('title', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'tenders', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tenders', 'users', ['modified_by'], ['id'])
    op.drop_column('tenders', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenders', type_='foreignkey')
    op.drop_constraint(None, 'tenders', type_='foreignkey')
    op.drop_column('tenders', 'title')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'contract_details', type_='foreignkey')
    op.drop_constraint(None, 'contract_clauses', type_='foreignkey')
    op.drop_constraint(None, 'contract_clauses', type_='foreignkey')
    # ### end Alembic commands ###
