"""empty message

Revision ID: 84a704ad14b3
Revises: 25965ad35599
Create Date: 2021-08-21 21:03:30.884767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a704ad14b3'
down_revision = '25965ad35599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_clauses', sa.Column('clause_title', sa.String(length=400), nullable=True))
    op.add_column('contract_clauses', sa.Column('clause_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_clauses', 'clause_body')
    op.drop_column('contract_clauses', 'clause_title')
    # ### end Alembic commands ###
