"""empty message

Revision ID: 866b11baa012
Revises: 00550daa5fc5
Create Date: 2021-08-24 09:07:28.294419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866b11baa012'
down_revision = '00550daa5fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('status_comments', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'status_comments')
    # ### end Alembic commands ###
