"""empty message

Revision ID: 9ce7ad9092bc
Revises: 3eff7f1dbb56
Create Date: 2021-08-15 20:44:59.882149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce7ad9092bc'
down_revision = '3eff7f1dbb56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clause_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clause_part', sa.String(length=200), nullable=True),
    sa.Column('clause_part_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clause_details', sa.Column('clause_part_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clause_details', 'clause_parts', ['clause_part_id'], ['id'])
    op.add_column('clauses', sa.Column('clause_title', sa.String(length=200), nullable=True))
    op.drop_column('clauses', 'clause_part_name')
    op.drop_column('clauses', 'clause_part')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clauses', sa.Column('clause_part', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('clauses', sa.Column('clause_part_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('clauses', 'clause_title')
    op.drop_constraint(None, 'clause_details', type_='foreignkey')
    op.drop_column('clause_details', 'clause_part_id')
    op.drop_table('clause_parts')
    # ### end Alembic commands ###
