"""empty message

Revision ID: ce4820ff6b02
Revises: 9ce7ad9092bc
Create Date: 2021-08-15 23:09:56.340018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4820ff6b02'
down_revision = '9ce7ad9092bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clause_details', sa.Column('has_table', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clause_details', 'has_table')
    # ### end Alembic commands ###
