"""empty message

Revision ID: e0e2e9cb41a5
Revises: d73baf5f0211
Create Date: 2021-08-10 11:05:14.206181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e2e9cb41a5'
down_revision = 'd73baf5f0211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_clause_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_clause_id', sa.Integer(), nullable=False),
    sa.Column('clause_part', sa.String(length=200), nullable=True),
    sa.Column('clause_part_name', sa.String(length=200), nullable=True),
    sa.Column('clause_part_detail', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_clause_id'], ['contract_clauses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contract_clauses', sa.Column('contract_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contract_clauses', 'contracts', ['contract_id'], ['id'])
    op.drop_column('contract_clauses', 'department_id')
    op.drop_column('contract_clauses', 'clause_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_clauses', sa.Column('clause_details', sa.VARCHAR(length=800), autoincrement=False, nullable=True))
    op.add_column('contract_clauses', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contract_clauses', type_='foreignkey')
    op.drop_column('contract_clauses', 'contract_id')
    op.drop_table('contract_clause_details')
    # ### end Alembic commands ###
