"""empty message

Revision ID: f05ebcf26ea2
Revises: eda8b98c095b
Create Date: 2021-08-06 11:21:53.891284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05ebcf26ea2'
down_revision = 'eda8b98c095b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_no', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.Integer(), nullable=True),
    sa.Column('contract_entity_purchaser_id', sa.Integer(), nullable=False),
    sa.Column('contract_entity_supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_entity_purchaser_id'], ['contract_entities.id'], ),
    sa.ForeignKeyConstraint(['contract_entity_supplier_id'], ['contract_entities.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'contract_products', 'contracts', ['contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract_products', type_='foreignkey')
    op.drop_table('contracts')
    op.drop_table('contract_entities')
    # ### end Alembic commands ###
